# Generated by Django 4.0.2 on 2022-03-25 12:53

import backend.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0003_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=backend.storage_backends.MediaStorage(), upload_to='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload', to='DocumentManagement.document')),
            ],
        ),
    ]
