# Generated by Django 4.0.2 on 2022-03-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0004_remove_document_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DocumentManagement.document'),
        ),
    ]
