# Generated by Django 4.0.2 on 2022-03-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0006_delete_file'),
        ('DocumentProcessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=65)),
                ('left', models.IntegerField()),
                ('top', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocumentManagement.document')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocumentProcessing.file')),
            ],
        ),
    ]
