# Generated by Django 4.0.2 on 2022-04-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentProcessing', '0002_documentword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentword',
            old_name='height',
            new_name='bottom',
        ),
        migrations.RenameField(
            model_name='documentword',
            old_name='width',
            new_name='right',
        ),
    ]
