# Generated by Django 4.0.2 on 2022-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentProcessing', '0003_rename_height_documentword_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='highlight',
            field=models.TextField(blank=True),
        ),
    ]
