# Generated by Django 4.0.2 on 2022-03-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabularyManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyset',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='studyset',
            name='owner_id',
        ),
        migrations.CreateModel(
            name='StudySetWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=65)),
                ('translation', models.CharField(blank=True, max_length=65)),
                ('definition', models.CharField(blank=True, max_length=65)),
                ('parent_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VocabularyManagement.studyset')),
            ],
        ),
    ]
