# Generated by Django 4.0.2 on 2022-04-02 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VocabularyManagement', '0002_remove_studyset_date_added_remove_studyset_owner_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyset',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
