# Generated by Django 4.0.2 on 2022-04-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VocabularyManagement', '0004_alter_studyset_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyset',
            name='owner_id',
        ),
    ]
