# Generated by Django 4.0.2 on 2022-04-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VocabularyManagement', '0011_studysetword_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysetword',
            name='owner_id',
        ),
    ]
