# Generated by Django 4.0.2 on 2022-04-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabularyManagement', '0014_studysetword_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysetword',
            name='definition',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
