# Generated by Django 4.0.2 on 2022-04-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0006_delete_file'),
        ('VocabularyManagement', '0015_alter_studysetword_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyset',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DocumentManagement.document'),
        ),
    ]
