# Generated by Django 4.0.2 on 2022-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabularyManagement', '0016_alter_studyset_generated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysetword',
            name='parent_set',
        ),
        migrations.AddField(
            model_name='studysetword',
            name='parent_set',
            field=models.ManyToManyField(to='VocabularyManagement.StudySet'),
        ),
    ]
