# Generated by Django 4.0.2 on 2022-04-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabularyManagement', '0017_remove_studysetword_parent_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysetword',
            name='parent_set',
        ),
        migrations.AddField(
            model_name='studysetword',
            name='parent_set',
            field=models.ForeignKey(default=113, on_delete=django.db.models.deletion.CASCADE, to='VocabularyManagement.studyset'),
            preserve_default=False,
        ),
    ]
